"""Selector generator worker - generates extraction selectors using LLM"""
import asyncio
from uuid import UUID, uuid4
from datetime import datetime
import httpx
from sqlalchemy import select
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker

from app.celery_app import celery_app
from app.config import settings
from app.models import Blueprint, Selector, Job
from app.services.llm_service import llm_service


async def _generate_selectors_async(blueprint_id: str, job_id: str, fields: list):
    """Async selector generation logic"""
    engine = create_async_engine(settings.DATABASE_URL)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    
    async with async_session() as db:
        # Get blueprint
        blueprint_stmt = select(Blueprint).where(Blueprint.blueprint_id == UUID(blueprint_id))
        result = await db.execute(blueprint_stmt)
        blueprint = result.scalar_one_or_none()
        
        if not blueprint:
            return {"error": "Blueprint not found"}
        
        # Get job
        job_stmt = select(Job).where(Job.job_id == UUID(job_id))
        result = await db.execute(job_stmt)
        job = result.scalar_one_or_none()
        
        if not job:
            return {"error": "Job not found"}
        
        # Update job
        job.status = "running"
        job.started_at = datetime.utcnow()
        await db.commit()
        
        try:
            # Fetch site HTML (in real app, cache this)
            from app.models import Site
            site_stmt = select(Site).where(Site.site_id == blueprint.site_id)
            result = await db.execute(site_stmt)
            site = result.scalar_one_or_none()
            
            url = f"https://{site.domain}"
            async with httpx.AsyncClient(timeout=15.0, follow_redirects=True) as client:
                response = await client.get(url, headers={"User-Agent": "Mozilla/5.0"})
                html = response.text[:5000]  # Use first 5K chars for selector gen
            
            # Generate selectors for each field
            selectors_created = []
            for field_name in fields:
                selector_result = await llm_service.generate_selectors(html, field_name)
                
                if selector_result.get("success"):
                    # Parse LLM response and create selector
                    selector = Selector(
                        selector_id=uuid4(),
                        blueprint_id=UUID(blueprint_id),
                        field_name=field_name,
                        css_selector=f".{field_name}",  # Simplified; parse from LLM in production
                        confidence=0.8,
                        generation_method="llm",
                        test_count=0,
                        test_failures=0,
                        notes=f"Generated by LLM for field: {field_name}"
                    )
                    db.add(selector)
                    selectors_created.append(field_name)
            
            # Update blueprint with selectors
            blueprint.selectors_data = {
                "fields": fields,
                "generated_count": len(selectors_created),
                "timestamp": datetime.utcnow().isoformat()
            }
            
            # Update job
            job.status = "success"
            job.ended_at = datetime.utcnow()
            job.result = {
                "blueprint_id": blueprint_id,
                "selectors_generated": len(selectors_created),
                "fields": selectors_created
            }
            
            if job.started_at:
                duration = (job.ended_at - job.started_at).total_seconds()
                job.duration_seconds = int(duration)
            
            await db.commit()
            
            return {
                "success": True,
                "blueprint_id": blueprint_id,
                "selectors_generated": len(selectors_created),
                "fields": selectors_created
            }
            
        except Exception as e:
            job.status = "failed"
            job.ended_at = datetime.utcnow()
            job.error_message = str(e)
            await db.commit()
            
            return {"success": False, "error": str(e)}
        
        finally:
            await engine.dispose()


@celery_app.task(name="workers.generate_selectors", bind=True)
def generate_selectors(self, blueprint_id: str, job_id: str, fields: list = None):
    """Celery task to generate selectors"""
    if fields is None:
        fields = ["title", "price", "description", "image"]
    
    try:
        result = asyncio.run(_generate_selectors_async(blueprint_id, job_id, fields))
        return result
    except Exception as e:
        return {"success": False", "error": str(e)}

